/** @type {import('tailwindcss').Config} */
export default {
  content: [
  "./index.html",
  "./about/index.html",
  "./blog/index.html",
  "./contact/index.html",
  "./kruger-national-park/index.html",
  "./kruger-national-park/safaris/index.html",
  "./kruger-national-park/all-inclusive-safari-packages/index.html",
  "./kruger-national-park/all-inclusive-safari-packages/5-day-private-safari/index.html",
  "./kruger-national-park/all-inclusive-safari-packages/6-day-private-safari/index.html",
  "./kruger-national-park/all-inclusive-safari-packages/7-day-private-safari/index.html",
  "./kruger-national-park/classic-safari-packages/index.html",
  "./kruger-national-park/classic-safari-packages/5-day-private-safari/index.html",
  "./kruger-national-park/classic-safari-packages/6-day-private-safari/index.html",
  "./kruger-national-park/classic-safari-packages/7-day-private-safari/index.html",
  "./kruger-national-park/photographic-safari/index.html",
  "./kruger-national-park/safari-on-film/index.html",
  "./kruger-national-park/guide/index.html",
  "./kruger-national-park/malaria/index.html",
  "./kruger-national-park/airports/index.html",
  "./kruger-national-park/airports/eastgate/index.html",
  "./kruger-national-park/airports/kmia/index.html",
  "./kruger-national-park/airports/skukuza/index.html",
  "./kruger-national-park/weather/index.html",
  "./kruger-national-park/weather/october/index.html",
  "./kruger-national-park/mammals/index.html",
  "./kruger-national-park/mammals/big-5/index.html",
  "./kruger-national-park/mammals/lion/index.html",
  "./kruger-national-park/mammals/leopard/index.html",
  "./kruger-national-park/mammals/buffalo/index.html",
  "./kruger-national-park/mammals/elephant/index.html",
  "./kruger-national-park/mammals/white-rhinoceros/index.html",
  "./kruger-national-park/mammals/black-rhinoceros/index.html",
  "./kruger-national-park/mammals/rhinoceros/index.html",
  "./difference-between-white-and-black-rhino/index.html",
  "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        linen: 'rgb(254, 252, 250)',
      },
      fontFamily: {
        avenir: ['"Avenir Light"', 'system-ui', 'sans-serif'],
        nunito: ['"Nunito Regular"', 'system-ui', 'sans-serif'],
        playfair: ['"Playfair Display"', 'serif'],
      },
    },
  },
  plugins: [],
}