/** @type {import('tailwindcss').Config} */
export default {
  content: [
  "./index.html",
  "./about/index.html",
  "./best-time-to-visit-kruger-national-park/index.html",
  "./birding/index.html",
  "./birding/kruger-national-park/index.html",
  "./blog/index.html",
  "./contact/index.html",
  "./kruger-national-park/index.html",
  "./kruger-national-park/safari-packages/index.html",
  "./kruger-national-park/safari-all-inclusive-packages/index.html",
  "./kruger-national-park/safari-all-inclusive-packages/5-day-private-safari/index.html",
  "./kruger-national-park/safari-all-inclusive-packages/6-day-private-safari/index.html",
  "./kruger-national-park/safari-all-inclusive-packages/7-day-private-safari/index.html",
  "./kruger-national-park/private-safaris/index.html",
  "./kruger-national-park/private-safaris/5-day/index.html",
  "./kruger-national-park/private-safaris/6-day/index.html",
  "./kruger-national-park/private-safaris/7-day/index.html",
  "./kruger-national-park/photographic-safari/index.html",
  "./kruger-national-park/safari-on-film/index.html",
  "./kruger-national-park/3-day-safari/index.html",
  "./kruger-national-park/guide/index.html",
  "./kruger-national-park/malaria/index.html",
  "./kruger-national-park/airports/index.html",
  "./kruger-national-park/airports/eastgate/index.html",
  "./kruger-national-park/airports/kmia/index.html",
  "./kruger-national-park/airports/skukuza/index.html",
  "./kruger-national-park/weather/index.html",
  "./kruger-national-park/weather/january/index.html",
  "./kruger-national-park/weather/february/index.html",
  "./kruger-national-park/weather/march/index.html",
  "./kruger-national-park/weather/april/index.html",
  "./kruger-national-park/weather/may/index.html",
  "./kruger-national-park/weather/june/index.html",
  "./kruger-national-park/weather/july/index.html",
  "./kruger-national-park/weather/august/index.html",
  "./kruger-national-park/weather/september/index.html",
  "./kruger-national-park/weather/october/index.html",
  "./kruger-national-park/weather/november/index.html",
  "./kruger-national-park/weather/december/index.html",
  "./kruger-national-park/mammals/index.html",
  "./kruger-national-park/mammals/big-5/index.html",
  "./kruger-national-park/mammals/lion/index.html",
  "./kruger-national-park/mammals/leopard/index.html",
  "./kruger-national-park/mammals/buffalo/index.html",
  "./kruger-national-park/mammals/elephant/index.html",
  "./kruger-national-park/mammals/white-rhinoceros/index.html",
  "./kruger-national-park/mammals/black-rhinoceros/index.html",
  "./kruger-national-park/mammals/rhinoceros/index.html",
  "./difference-between-white-and-black-rhino/index.html",
  "./what-to-wear-on-a-safari/index.html",
  "./what-to-bring-on-an-african-safari/index.html",
  "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        linen: 'rgb(254, 252, 250)',
      },
      fontFamily: {
        avenir: ['"Avenir Light"', 'system-ui', 'sans-serif'],
        crimson: ['"Crimson Text"', 'serif'],
      },
    },
  },
  plugins: [],
}