import { defineConfig } from 'vite'
import path from 'path'

export default defineConfig({
  base: '/',
  build: {
    outDir: 'dist',
    rollupOptions: {
      input: {
        main: path.resolve(__dirname, 'index.html'),
        aardvark: path.resolve(__dirname, 'aardvark/index.html'),
        about: path.resolve(__dirname, 'about/index.html'),
        africanbuffalo: path.resolve(__dirname, 'african-buffalo/index.html'),
        africanbushelephant: path.resolve(__dirname, 'african-bush-elephant/index.html'),
        africanleopard: path.resolve(__dirname, 'african-leopard/index.html'),
        africanwildcat: path.resolve(__dirname, 'african-wildcat/index.html'),
        bateleur: path.resolve(__dirname, 'bateleur/index.html'),
        besttimetovisitkrugernationalpark: path.resolve(__dirname, 'best-time-to-visit-kruger-national-park/index.html'),
        birding: path.resolve(__dirname, 'birding/index.html'),
        birdingkrugernationalpark: path.resolve(__dirname, 'birding/kruger-national-park/index.html'),
        birdingkrugernationalparknorthtosouth: path.resolve(__dirname, 'birding/kruger-national-park/north-to-south/index.html'),
        birdingkrugernationalparknorthern: path.resolve(__dirname, 'birding/kruger-national-park/northern/index.html'),
        birdingkrugernationalparksouthern: path.resolve(__dirname, 'birding/kruger-national-park/southern/index.html'),
        blackbackedjackal: path.resolve(__dirname, 'black-backed-jackal/index.html'),
        blackrhinoceros: path.resolve(__dirname, 'black-rhinoceros/index.html'),
        blog: path.resolve(__dirname, 'blog/index.html'),
        bluewildebeest: path.resolve(__dirname, 'blue-wildebeest/index.html'),
        brownheadedparrot: path.resolve(__dirname, 'brown-headed-parrot/index.html'),
        burchellszebra: path.resolve(__dirname, 'burchells-zebra/index.html'),
        bushbuck: path.resolve(__dirname, 'bushbuck/index.html'),
        capeporcupine: path.resolve(__dirname, 'cape-porcupine/index.html'),
        caracal: path.resolve(__dirname, 'caracal/index.html'),
        chacmababoon: path.resolve(__dirname, 'chacma-baboon/index.html'),
        cheetah: path.resolve(__dirname, 'cheetah/index.html'),
        civet: path.resolve(__dirname, 'civet/index.html'),
        commonduiker: path.resolve(__dirname, 'common-duiker/index.html'),
        contact: path.resolve(__dirname, 'contact/index.html'),
        crestedbarbet: path.resolve(__dirname, 'crested-barbet/index.html'),
        whitevsblackrhino: path.resolve(__dirname, 'difference-between-white-and-black-rhino/index.html'),
        dwarfmongoose: path.resolve(__dirname, 'dwarf-mongoose/index.html'),
        eland: path.resolve(__dirname, 'eland/index.html'),
        greaterkudu: path.resolve(__dirname, 'greater-kudu/index.html'),
        hippopotamus: path.resolve(__dirname, 'hippopotamus/index.html'),
        honeybadger: path.resolve(__dirname, 'honey-badger/index.html'),
        impala: path.resolve(__dirname, 'impala/index.html'),
        klipspringer: path.resolve(__dirname, 'klipspringer/index.html'),
        krugernational3daysafari: path.resolve(__dirname, 'kruger-national-park/3-day-safari/index.html'),
        krugernationalparkairports: path.resolve(__dirname, 'kruger-national-park/airports/index.html'),
        krugernationalparkeastgate: path.resolve(__dirname, 'kruger-national-park/airports/eastgate/index.html'),
        krugernationalparkkmia: path.resolve(__dirname, 'kruger-national-park/airports/kmia/index.html'),
        krugernationalparkskukuza: path.resolve(__dirname, 'kruger-national-park/airports/skukuza/index.html'),
        krugernationalparkbirds: path.resolve(__dirname, 'kruger-national-park/birds/index.html'),
        krugernationalparkgrasses: path.resolve(__dirname, 'kruger-national-park/grasses/index.html'),
        krugernationalparkguide: path.resolve(__dirname, 'kruger-national-park/guide/index.html'),
        krugernationalparkmalaria: path.resolve(__dirname, 'kruger-national-park/malaria/index.html'),
        krugernationalparkmammals: path.resolve(__dirname, 'kruger-national-park/mammals/index.html'),
        krugernationalparkbig5: path.resolve(__dirname, 'kruger-national-park/mammals/big-5/index.html'),
        krugernationalparkphotographicsafari: path.resolve(__dirname, 'kruger-national-park/photographic-safari/index.html'),
        krugernationalparkclassicsafaris: path.resolve(__dirname, 'kruger-national-park/private-safaris/index.html'),
        krugernationalparksafaris5day: path.resolve(__dirname, 'kruger-national-park/private-safaris/5-day/index.html'),
        krugernationalparksafaris6day: path.resolve(__dirname, 'kruger-national-park/private-safaris/6-day/index.html'),
        krugernationalparksafaris7day: path.resolve(__dirname, 'kruger-national-park/private-safaris/7-day/index.html'),
        krugernationalparkrestcamps: path.resolve(__dirname, 'kruger-national-park/rest-camps/index.html'),
        krugernationalparksafariallinclusivepackages: path.resolve(__dirname, 'kruger-national-park/safari-all-inclusive-packages/index.html'),
        krugernationalparksafariallinclusivepackage5day: path.resolve(__dirname, 'kruger-national-park/safari-all-inclusive-packages/5-day-private-safari/index.html'),
        krugernationalparksafariallinclusivepackage6day: path.resolve(__dirname, 'kruger-national-park/safari-all-inclusive-packages/6-day-private-safari/index.html'),
        krugernationalparksafariallinclusivepackage7day: path.resolve(__dirname, 'kruger-national-park/safari-all-inclusive-packages/7-day-private-safari/index.html'),
        krugernationalparksafarionfilm: path.resolve(__dirname, 'kruger-national-park/safari-on-film/index.html'),
        krugernationalparkprivatesafaris: path.resolve(__dirname, 'kruger-national-park/safari-packages/index.html'),
        krugernationalparkweather: path.resolve(__dirname, 'kruger-national-park/weather/index.html'),
        krugernationalparkweatherapril: path.resolve(__dirname, 'kruger-national-park/weather/april/index.html'),
        krugernationalparkweatheraugust: path.resolve(__dirname, 'kruger-national-park/weather/august/index.html'),
        krugernationalparkweatherdecember: path.resolve(__dirname, 'kruger-national-park/weather/december/index.html'),
        krugernationalparkweatherfebruary: path.resolve(__dirname, 'kruger-national-park/weather/february/index.html'),
        krugernationalparkweatherjanuary: path.resolve(__dirname, 'kruger-national-park/weather/january/index.html'),
        krugernationalparkweatherjuly: path.resolve(__dirname, 'kruger-national-park/weather/july/index.html'),
        krugernationalparkweatherjune: path.resolve(__dirname, 'kruger-national-park/weather/june/index.html'),
        krugernationalparkweathermarch: path.resolve(__dirname, 'kruger-national-park/weather/march/index.html'),
        krugernationalparkweathermay: path.resolve(__dirname, 'kruger-national-park/weather/may/index.html'),
        krugernationalparkweathernovember: path.resolve(__dirname, 'kruger-national-park/weather/november/index.html'),
        krugernationalparkweatheroctober: path.resolve(__dirname, 'kruger-national-park/weather/october/index.html'),
        krugernationalparkweatherseptember: path.resolve(__dirname, 'kruger-national-park/weather/september/index.html'),
        krugernationalparkwildlife: path.resolve(__dirname, 'kruger-national-park/wildlife/index.html'),
        largespottedgenet: path.resolve(__dirname, 'large-spotted-genet/index.html'),
        lessergalago: path.resolve(__dirname, 'lesser-galago/index.html'),
        lilacbreastedroller: path.resolve(__dirname, 'lilac-breasted-roller/index.html'),
        lion: path.resolve(__dirname, 'lion/index.html'),
        nyala: path.resolve(__dirname, 'nyala/index.html'),
        pundamariarestcamp: path.resolve(__dirname, 'punda-maria-rest-camp/index.html'),
        purpleroller: path.resolve(__dirname, 'purple-roller/index.html'),
        reedcormorant: path.resolve(__dirname, 'reed-cormorant/index.html'),
        rockhyrax: path.resolve(__dirname, 'rock-hyrax/index.html'),
        scrubhare: path.resolve(__dirname, 'scrub-hare/index.html'),
        southerngiraffe: path.resolve(__dirname, 'southern-giraffe/index.html'),
        spottedhyena: path.resolve(__dirname, 'spotted-hyena/index.html'),
        treesquirrel: path.resolve(__dirname, 'tree-squirrel/index.html'),
        verreauxseagleowl: path.resolve(__dirname, 'verreauxs-eagle-owl/index.html'),
        vervetmonkey: path.resolve(__dirname, 'vervet-monkey/index.html'),
        warthog: path.resolve(__dirname, 'warthog/index.html'),
        waterbuck: path.resolve(__dirname, 'waterbuck/index.html'),
        whattobringonanafricansafari: path.resolve(__dirname, 'what-to-bring-on-a-safari/index.html'),
        whattowearonsafari: path.resolve(__dirname, 'what-to-wear-on-a-safari/index.html'),
        whiterhinoceros: path.resolve(__dirname, 'white-rhinoceros/index.html'),
        wilddog: path.resolve(__dirname, 'wild-dog/index.html'),
        worsttimetovisitkrugernationalpark: path.resolve(__dirname, 'worst-time-to-visit-kruger-national-park/index.html')
      }
    }
  }
})